"""
Tests for the ``update_cols`` parameter of the SQL engine write path.

``update_cols`` (``mode=auto`` + ``match_by``) lets callers restrict the
columns that are mutated during a MERGE upsert.  The other write modes
(append, overwrite, truncate) ignore it.

Structure
---------
Unit tests (no live workspace)
    All IO is mocked so the SQL generated by ``arrow_insert_into`` can be
    inspected without any Databricks connection.

Integration tests (``requires_databricks``)
    :class:`TestUpdateColsIntegration` creates a real Delta table, exercises
    all three cases (default / explicit subset / empty), and verifies the
    resulting row data via ``to_arrow_table()``.
"""

from __future__ import annotations

import contextlib
from unittest.mock import MagicMock, patch

import pyarrow as pa
import pytest

from yggdrasil.databricks.client import DatabricksClient
from yggdrasil.databricks.sql.engine import SQLEngine
from yggdrasil.databricks.sql.table import Table

from ..conftest import DatabricksCase, requires_databricks

# ── shared fixtures & helpers ─────────────────────────────────────────────────

SCHEMA = pa.schema([
    pa.field("id",    pa.int64()),
    pa.field("name",  pa.string()),
    pa.field("value", pa.float64()),
])

SAMPLE = pa.table({
    "id":    pa.array([1, 2, 3], type=pa.int64()),
    "name":  ["a", "b", "c"],
    "value": pa.array([1.0, 2.0, 3.0], type=pa.float64()),
})

_LOCATION = "`main`.`sales`.`test_update_cols`"


@pytest.fixture()
def mock_client():
    return MagicMock(spec=DatabricksClient)


@pytest.fixture()
def mock_table():
    """Pre-configured Table mock backed by SCHEMA."""
    tbl = MagicMock(spec=Table)
    tbl.arrow_schema = SCHEMA
    tbl.full_name.return_value = _LOCATION
    tbl.full_name.side_effect = lambda safe=None: _LOCATION
    tbl.catalog_name = "main"
    tbl.schema_name = "sales"
    tbl.table_name = "test_update_cols"
    tbl.ensure_created.return_value = tbl
    return tbl


@contextlib.contextmanager
def _capture_arrow_sqls(engine: SQLEngine, table: MagicMock):
    """
    Patch all heavy IO inside ``arrow_insert_into`` and collect every SQL
    string that would be passed to ``engine.execute()``.

    ``SQLEngine`` is a frozen dataclass, so we patch at the *class* level.
    """
    fake_path = MagicMock()
    fake_path.__str__ = lambda _: (
        "/Volumes/main/sales/tmp/.sql/main/sales/test_update_cols/"
        "tmp-1774938955-1774942555-5ba89ace.parquet"
    )
    fake_path.write_bytes = MagicMock()
    fake_path.remove = MagicMock()
    fake_path.parent = MagicMock()
    fake_path.parent.mkdir = MagicMock()

    fake_staging = MagicMock()
    fake_staging.path = fake_path
    fake_staging.register_shutdown_cleanup = MagicMock()
    fake_staging.cleanup = MagicMock()

    mock_mio = MagicMock()
    mock_mio.buffer.memoryview.return_value = b""

    mock_bio_instance = MagicMock()
    mock_bio_instance.__enter__ = MagicMock(return_value=MagicMock())
    mock_bio_instance.__exit__ = MagicMock(return_value=False)

    captured: list[str] = []

    # Class-level patches work on frozen dataclasses; instance-level do not.
    def _fake_execute(sql, **_kw):
        captured.append(sql.strip())
        return MagicMock()

    with (
        patch("yggdrasil.databricks.sql.engine.StagingPath.for_table", return_value=fake_staging),
        patch("yggdrasil.databricks.sql.engine.BytesIO", return_value=mock_bio_instance),
        patch("yggdrasil.databricks.sql.engine.MediaIO") as mock_MediaIO,
        patch("yggdrasil.databricks.sql.engine.Job"),
        patch.object(SQLEngine, "execute", side_effect=_fake_execute),
    ):
        mock_MediaIO.make.return_value = mock_mio
        yield captured


def _run(engine, table, *, update_cols, mode="auto", match_by=None):
    """Call arrow_insert_into and return captured SQL statements."""
    with _capture_arrow_sqls(engine, table) as sqls:
        engine.arrow_insert_into(
            data=SAMPLE,
            table=table,
            match_by=match_by or ["id"],
            update_cols=update_cols,
            mode=mode,
        )
    return sqls


# ===========================================================================
# Unit — arrow_insert_into SQL generation
# ===========================================================================


class TestUpdateColsArrowSQL:
    """Unit tests — verify the MERGE SQL produced by arrow_insert_into."""

    @pytest.fixture(autouse=True)
    def _engine(self, mock_client, mock_table):
        self.engine = SQLEngine(client=mock_client, catalog_name="main", schema_name="sales")
        self.table = mock_table

    def test_default_updates_all_non_key_columns(self):
        """update_cols=None → all non-key columns appear in UPDATE SET."""
        sqls = _run(self.engine, self.table, update_cols=None)
        assert len(sqls) == 1
        merge = sqls[0]
        assert "WHEN MATCHED THEN UPDATE SET" in merge
        assert "`name`" in merge
        assert "`value`" in merge
        # key column must NOT appear in UPDATE SET
        assert "T.`id`" not in merge.split("WHEN MATCHED")[1]

    def test_explicit_subset_updates_only_those_columns(self):
        """update_cols=['value'] → only value in UPDATE SET, name absent."""
        sqls = _run(self.engine, self.table, update_cols=["value"])
        merge = sqls[0]
        assert "WHEN MATCHED THEN UPDATE SET" in merge
        assert "T.`value` = S.`value`" in merge
        # name must NOT appear in the UPDATE SET clause
        update_part = merge.split("WHEN MATCHED THEN UPDATE SET")[1].split("WHEN NOT MATCHED")[0]
        assert "`name`" not in update_part

    def test_empty_list_omits_update_clause(self):
        """update_cols=[] → no WHEN MATCHED UPDATE, still inserts new rows."""
        sqls = _run(self.engine, self.table, update_cols=[])
        merge = sqls[0]
        assert "WHEN MATCHED THEN UPDATE SET" not in merge
        assert "WHEN NOT MATCHED THEN INSERT" in merge

    def test_update_cols_not_applied_to_append_mode(self):
        """APPEND mode ignores update_cols; MERGE is insert-only."""
        sqls = _run(self.engine, self.table, update_cols=["value"], mode="append")
        merge = sqls[0]
        assert "WHEN MATCHED" not in merge
        assert "WHEN NOT MATCHED THEN INSERT" in merge

    def test_update_cols_not_applied_to_truncate_mode(self):
        """TRUNCATE mode: DELETE + INSERT, no MERGE UPDATE clause."""
        sqls = _run(self.engine, self.table, update_cols=["value"], mode="truncate")
        assert len(sqls) == 2
        assert sqls[0].startswith("DELETE FROM")
        assert sqls[1].startswith("INSERT INTO")
        assert "WHEN MATCHED" not in " ".join(sqls)

    def test_update_cols_insert_row_always_present(self):
        """The WHEN NOT MATCHED INSERT clause is always present regardless of update_cols."""
        for uc in [None, ["value"], []]:
            sqls = _run(self.engine, self.table, update_cols=uc)
            assert "WHEN NOT MATCHED THEN INSERT" in sqls[0], f"failed for update_cols={uc!r}"

    def test_merge_uses_null_safe_equality_on_key(self):
        """Keys in ON condition should use <=> (null-safe)."""
        sqls = _run(self.engine, self.table, update_cols=None)
        assert "T.`id` <=> S.`id`" in sqls[0]


# ===========================================================================
# Unit — insert_into propagates update_cols to arrow_insert_into
# ===========================================================================


class TestUpdateColsPropagation:
    """Verify that insert_into forwards update_cols to the underlying path."""

    @pytest.fixture(autouse=True)
    def _setup(self, mock_client):
        self.engine = SQLEngine(client=mock_client)

    def test_arrow_path_receives_update_cols(self, mock_table):
        with (
            patch.object(SQLEngine, "arrow_insert_into") as mock_arrow,
            patch("yggdrasil.databricks.sql.engine.PyEnv") as mock_pyenv,
        ):
            mock_pyenv.spark_session.return_value = None
            self.engine.insert_into(
                data=SAMPLE,
                table=mock_table,
                match_by=["id"],
                update_cols=["value"],
                mode="auto",
            )
        mock_arrow.assert_called_once()
        _, kwargs = mock_arrow.call_args
        assert kwargs.get("update_cols") == ["value"]

    def test_spark_path_receives_update_cols(self, mock_table):
        mock_spark = MagicMock()
        with patch.object(SQLEngine, "spark_insert_into") as mock_spark_fn:
            self.engine.insert_into(
                data=SAMPLE,
                table=mock_table,
                match_by=["id"],
                update_cols=["name"],
                mode="auto",
                spark_session=mock_spark,
            )
        mock_spark_fn.assert_called_once()
        _, kwargs = mock_spark_fn.call_args
        assert kwargs.get("update_cols") == ["name"]


# ===========================================================================
# Integration — requires live Databricks workspace
# ===========================================================================

pytestmark_integration = [requires_databricks, pytest.mark.integration]

_TABLE = "test_engine_update_cols"

_INITIAL = pa.table({
    "id":    pa.array([1, 2, 3], type=pa.int64()),
    "name":  ["Alice", "Bob", "Charlie"],
    "value": pa.array([100.0, 200.0, 300.0], type=pa.float64()),
})

_UPSERT = pa.table({
    "id":    pa.array([1, 4], type=pa.int64()),   # row 1 exists, row 4 is new
    "name":  ["Alice-UPDATED", "Dave"],
    "value": pa.array([999.0, 400.0], type=pa.float64()),
})


class TestUpdateColsIntegration(DatabricksCase):
    """Integration tests that hit a real Delta table in the test catalog."""

    pytestmark = pytestmark_integration

    @classmethod
    def setUpClass(cls) -> None:
        super().setUpClass()
        cls.engine = cls.workspace.sql(catalog_name="trading", schema_name="unittest")
        # Drop from a prior failed run if needed
        cls.engine.drop_table(table_name=_TABLE, raise_error=False)
        # Create fresh table
        cls.engine.insert_into(_INITIAL, table_name=_TABLE, mode="overwrite")

    @classmethod
    def tearDownClass(cls) -> None:
        cls.engine.drop_table(table_name=_TABLE, raise_error=False)
        super().tearDownClass()

    def _read(self) -> pa.Table:
        result = self.engine.execute(
            f"SELECT id, name, value FROM {self.engine.tables.table(table_name=_TABLE).full_name(safe=True)}"
            f" ORDER BY id"
        )
        return result.to_arrow_table()

    def _reset(self):
        """Restore the table to its initial state."""
        self.engine.insert_into(_INITIAL, table_name=_TABLE, mode="overwrite")

    # ── default behaviour (update all non-key columns) ───────────────────────

    def test_default_updates_all_non_key_columns(self):
        self._reset()
        self.engine.insert_into(
            _UPSERT,
            table_name=_TABLE,
            mode="auto",
            match_by=["id"],
            # update_cols=None  → default
        )
        rows = {r["id"].as_py(): r for r in self._read().to_pylist()}

        # row 1: both name and value should be updated
        self.assertEqual(rows[1]["name"], "Alice-UPDATED")
        self.assertEqual(rows[1]["value"], 999.0)
        # row 2: untouched
        self.assertEqual(rows[2]["name"], "Bob")
        self.assertEqual(rows[2]["value"], 200.0)
        # row 4: inserted
        self.assertIn(4, rows)
        self.assertEqual(rows[4]["name"], "Dave")

    # ── explicit subset: only value updated, name unchanged ──────────────────

    def test_explicit_update_cols_restricts_update(self):
        self._reset()
        self.engine.insert_into(
            _UPSERT,
            table_name=_TABLE,
            mode="auto",
            match_by=["id"],
            update_cols=["value"],   # ← only update the value column
        )
        rows = {r["id"].as_py(): r for r in self._read().to_pylist()}

        # row 1: value updated, but name must stay "Alice" (not "Alice-UPDATED")
        self.assertEqual(rows[1]["name"], "Alice")
        self.assertEqual(rows[1]["value"], 999.0)
        # row 4: fully inserted (new row carries all columns)
        self.assertEqual(rows[4]["name"], "Dave")
        self.assertEqual(rows[4]["value"], 400.0)

    # ── empty list: matched rows are not updated at all ──────────────────────

    def test_empty_update_cols_skips_update_for_matched_rows(self):
        self._reset()
        self.engine.insert_into(
            _UPSERT,
            table_name=_TABLE,
            mode="auto",
            match_by=["id"],
            update_cols=[],   # ← no columns to update
        )
        rows = {r["id"].as_py(): r for r in self._read().to_pylist()}

        # row 1: original values must be untouched
        self.assertEqual(rows[1]["name"], "Alice")
        self.assertEqual(rows[1]["value"], 100.0)
        # row 4: new row is inserted regardless
        self.assertIn(4, rows)

    # ── update_cols ignored in non-upsert modes ──────────────────────────────

    def test_update_cols_ignored_in_append_mode(self):
        """In APPEND mode the MERGE never fires an UPDATE; update_cols is irrelevant."""
        self._reset()
        # Attempt to insert a row whose id already exists: it should be skipped
        self.engine.insert_into(
            pa.table({"id": [1], "name": ["GHOST"], "value": [0.0]}),
            table_name=_TABLE,
            mode="append",
            match_by=["id"],
            update_cols=["value"],   # should have no effect in append mode
        )
        rows = {r["id"].as_py(): r for r in self._read().to_pylist()}
        self.assertEqual(rows[1]["name"], "Alice")   # unchanged
        self.assertEqual(rows[1]["value"], 100.0)    # unchanged

    def test_update_cols_ignored_in_truncate_mode(self):
        """TRUNCATE + match_by does DELETE + INSERT, not MERGE; update_cols is irrelevant."""
        self._reset()
        batch = pa.table({"id": [1], "name": ["NewAlice"], "value": [777.0]})
        self.engine.insert_into(
            batch,
            table_name=_TABLE,
            mode="truncate",
            match_by=["id"],
            update_cols=["value"],   # should have no effect in truncate mode
        )
        rows = {r["id"].as_py(): r for r in self._read().to_pylist()}
        # Row 1 was deleted then re-inserted from batch (full row)
        self.assertEqual(rows[1]["name"], "NewAlice")
        self.assertEqual(rows[1]["value"], 777.0)
        # Rows 2 and 3 were NOT in the batch → should still exist (only matching keys deleted)
        self.assertIn(2, rows)
        self.assertIn(3, rows)

