#!/usr/bin/env python3
"""Generate the ygg serverless environment spec that pairs the built wheel
with the matching Databricks serverless environment version.

Run right after ``uv build`` (see ``.github/workflows/publish.yml``). Writes
``environments/ygg/ygg-<version>-py<py>-serverless.yml`` — a Databricks
serverless ``Environment`` spec (``environment_version`` + ``dependencies``,
the field names the Jobs API / ``databricks.sdk`` ``Environment`` uses) whose:

* ``environment_version`` is the serverless runtime whose Python matches
  ``--python`` — so the pure-python ygg wheel installs cleanly and Python
  UDFs run (Spark Connect needs the client and server to share a minor
  Python); and
* ``dependencies`` install **only wheels, by path** — the ygg wheel first,
  then the bundled dependency wheels gathered from ``--wheel-dir`` /
  ``--wheel`` (databricks-sdk, polars + its compiled polars-runtime, orjson,
  xxhash). No index requirements: nothing is resolved from PyPI on the
  cluster; ``pyarrow`` (and the rest of the data stack) comes from the
  serverless base image.

Stdlib only — no install of ygg (or its heavy deps) is needed in CI. The
``python → serverless environment version`` mapping mirrors
:func:`yggdrasil.databricks.job.wheel.serverless_environment_version`; a test
(``tests/test_yggdrasil/test_databricks/test_serverless_env.py``) asserts the
two agree so they can't drift.
"""
from __future__ import annotations

import argparse
import tomllib
from pathlib import Path

# Databricks serverless environment versions, keyed by the runtime's Python
# minor; anything newer maps to the latest. KEEP IN SYNC with
# ``serverless_environment_version`` in
# ``python/src/yggdrasil/databricks/job/wheel.py`` (a test enforces it).
SERVERLESS_ENVIRONMENT_VERSION = "5"
_PY_MINOR_TO_ENV_VERSION = {10: "1", 11: "2"}


def serverless_environment_version(python_minor: int) -> str:
    """Serverless environment version whose runtime Python is ``3.<minor>``."""
    return _PY_MINOR_TO_ENV_VERSION.get(python_minor, SERVERLESS_ENVIRONMENT_VERSION)


def collect_wheels(
    version: str,
    *,
    wheel_dir: "str | Path | None" = None,
    extra_wheels: "list[str] | None" = None,
) -> "list[str]":
    """The wheel filenames the env installs, by path — ygg wheel first.

    Explicit ``--wheel`` names come next (in order), then every ``*.whl`` in
    ``--wheel-dir`` (sorted). Order-preserving de-dupe so a wheel passed both
    ways — or the ygg wheel sitting in the dir — appears once.
    """
    wheels = [f"ygg-{version}-py3-none-any.whl"]
    for name in extra_wheels or []:
        if name not in wheels:
            wheels.append(name)
    if wheel_dir is not None:
        for path in sorted(Path(wheel_dir).glob("*.whl")):
            if path.name not in wheels:
                wheels.append(path.name)
    return wheels


def build_yaml(version: str, python: str, wheels: "list[str]") -> str:
    """Render the serverless ``Environment`` spec as YAML text.

    *wheels* are installed in order, by path. Hand-rendered (no PyYAML
    dependency) — the shape is a single scalar plus a flat string list, so
    the output is trivially valid YAML.
    """
    minor = int(python.split(".")[1])
    env_version = serverless_environment_version(minor)
    lines = [
        "# Auto-generated by python/scripts/build_serverless_env.py — do not edit by hand.",
        f"# ygg {version} serverless environment for Python {python}.",
        "#",
        f"# environment_version {env_version} is the Databricks serverless runtime whose",
        f"# Python is {python}, so the pure-python ygg wheel installs cleanly and Python",
        "# UDFs run (Spark Connect needs a matching client Python). Dependencies are",
        "# wheels installed BY PATH only — the ygg wheel plus the bundled dependency",
        "# wheels (databricks-sdk, polars + its compiled polars-runtime, orjson, xxhash) —",
        "# so nothing is pip-resolved from the index on the cluster; pyarrow comes from",
        "# the serverless base image. Drop into a serverless job's environments[].spec",
        "# or a notebook environment specification.",
        f'environment_version: "{env_version}"',
        "dependencies:",
    ]
    lines.extend(f"  - {wheel}" for wheel in wheels)
    return "\n".join(lines) + "\n"


def main(argv: "list[str] | None" = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--python", default="3.12",
        help="target serverless runtime Python (X.Y); default 3.12",
    )
    parser.add_argument(
        "--version", default=None,
        help="ygg version; default reads python/pyproject.toml",
    )
    parser.add_argument(
        "--wheel-dir", default=None,
        help="directory of bundled dependency wheels to install by path "
             "(every *.whl in it is added after the ygg wheel)",
    )
    parser.add_argument(
        "--wheel", action="append", default=[], metavar="NAME",
        help="explicit bundled wheel filename to install by path (repeatable)",
    )
    parser.add_argument(
        "--pyproject", default=None,
        help="path to python/pyproject.toml; default resolved from this script",
    )
    parser.add_argument(
        "--out-dir", default=None,
        help="output directory; default <repo>/environments/ygg",
    )
    args = parser.parse_args(argv)

    # Paths are resolved from this file so the script writes to the repo's
    # ``environments/ygg`` regardless of the caller's working directory.
    here = Path(__file__).resolve()
    repo_root = here.parents[2]  # python/scripts/build_serverless_env.py -> repo root
    pyproject_path = (
        Path(args.pyproject) if args.pyproject else here.parents[1] / "pyproject.toml"
    )
    pyproject = tomllib.loads(pyproject_path.read_text())

    version = args.version or pyproject["project"]["version"]
    wheels = collect_wheels(version, wheel_dir=args.wheel_dir, extra_wheels=args.wheel)

    out_dir = Path(args.out_dir) if args.out_dir else repo_root / "environments" / "ygg"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"ygg-{version}-py{args.python}-serverless.yml"
    out_path.write_text(build_yaml(version, args.python, wheels))

    try:
        shown = out_path.relative_to(repo_root)
    except ValueError:
        shown = out_path
    print(f"wrote {shown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
